version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - funlen
    - gocritic
    - goconst
    - lll
    - unused
    - testpackage
    - dupl
  settings:
    lll:
      line-length: 250
    goconst:
      min-occurrences: 2
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 200
      tab-len: 16
output:
  formats:
    json:
      path: stderr
  sort-order:
    - severity
    - file
    - linter  
severity:
  default: error
  rules:
    - linters:
        - lll
        - funlen
        - errcheck
      severity: info
run:
  timeout: 10m
  relative-path-mode: gomod
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 4