name: lint

on:
  pull_request:
    paths:
      - "**.go"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: v2.1